# Generated by Django 3.0.8 on 2020-08-01 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0002_remove_file_upload_uploaded_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file_upload',
            name='document',
            field=models.FileField(upload_to='encode/'),
        ),
    ]
